-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 22:08:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_guerreirastech
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_guerreirastech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_guerreirastech` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_guerreirastech` ;

-- -----------------------------------------------------
-- Table `db_guerreirastech`.`tb_guerreiras_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_guerreirastech`.`tb_guerreiras_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_guerreirastech`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_guerreirastech`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categorias` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_guerreirastech`.`tb_post_feed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_guerreirastech`.`tb_post_feed` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `texto` TEXT NOT NULL,
  `foto` VARCHAR(255) NULL,
  `data` DATETIME NULL,
  `fonte` VARCHAR(255) NULL,
  `tb_guerreiras_user_id` BIGINT NOT NULL,
  `tb_categorias_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_post_feed_tb_guerreiras_user_idx` (`tb_guerreiras_user_id` ASC) VISIBLE,
  INDEX `fk_tb_post_feed_tb_categorias1_idx` (`tb_categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_post_feed_tb_guerreiras_user`
    FOREIGN KEY (`tb_guerreiras_user_id`)
    REFERENCES `db_guerreirastech`.`tb_guerreiras_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_post_feed_tb_categorias1`
    FOREIGN KEY (`tb_categorias_id`)
    REFERENCES `db_guerreirastech`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
